version: 2.1

orbs:
  node: circleci/node@5.0.2

aliases:
  - &restore-cache
    restore_cache:
      key: dependency-cache-{{ checksum "package.json" }}
  - &install-deps
    run:
      name: Install dependencies
      command: npm ci
  - &build-packages
    run:
      name: Build
      command: npm run build

jobs:
  build:
    executor: node/default
    working_directory: ~/nest
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Build
          command: npm run build

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
