export const FIREBASE_ADMIN_INSTANCE_TOKEN = 'FIREBASE_ADMIN_INSTANCE_TOKEN';
export const FIREBASE_ADMIN_APP = 'FIREBASE_ADMIN_APP';
export const ADMIN_MODULE_ID = 'ADMIN_MODULE_ID';
export const ADMIN_MODULE_OPTIONS = 'ADMIN_MODULE_OPTIONS';
